[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = 8c5b892bf752dbd2dc4740ac40b8ae93
#前16位偏移位
aes_iv = 882e04793b70601e
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 666