[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = 200b864374c460b327d409219d7f7165
#前16位偏移位
aes_iv = da30892999238df2
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 666