[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = e49cb5358681b14d2457077b652e236c
#前16位偏移位
aes_iv = 8c4fc955e8100b15
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 666