# Exported from Render on 2026-03-19T16:11:38Z
version: "1"
services:
- type: web
  name: pushnews
  runtime: rust
  repo: https://github.com/vcvvvc/nullmsg
  branch: msg_rust
  plan: free
  region: singapore
  buildCommand: ' cargo build --release'
  startCommand: cargo run --release
  autoDeployTrigger: "off"
