[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = a3d2b12569100ddfb65544e6c7994c3f
#前16位偏移位
aes_iv = c5eaa432c610f358
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 4ae43be24aa048aba017fea3585d16eb