[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = ed146d1ebdf75778b1e80eecdd4aadc6
#前16位偏移位
aes_iv = b3b93835056ba735
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 4ae43be24aa048aba017fea3585d16eb