[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = a9c95e54b79a40b86986a1e215a76229
#前16位偏移位
aes_iv = 5bc8dea798856e6a
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 4ae43be24aa048aba017fea3585d16eb