[DEFAULT]
#域名/ip
server_host =
#bark里的key
server_key =
#AES256 32位
aes_key = b9ee2cf22afffdbfba96a58a8d433059
#前16位偏移位
aes_iv = a6c4ca647aa7336e
[tkinsight]
#https://api.tokeninsight.com/reference/api-overview申请
api_key = 4ae43be24aa048aba017fea3585d16eb
